name: Expo Preview
on:
  pull_request:

jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.owner.login == 'satya164'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Comment preview
        uses: expo/expo-github-action/preview@v8
        with:
          working-directory: ./example
          command: eas update --non-interactive --auto
